package networking;

public enum RequestType {
    LOGIN, LOGOUT,
    GET_ALL_ROUTES, ADD_ROUTE, UPDATE_ROUTE, REMOVE_ROUTE,
    GET_ALL_STATIONS,
    GET_ALL_TRAINS, ADD_TRAIN, UPDATE_TRAIN, REMOVE_TRAIN
}
