package networking;

public enum RequestType {
    LOGIN, LOGOUT,
    GET_ALL_ROUTES, ADD_ROUTE, UPDATE_ROUTE, REMOVE_ROUTE,
    GET_ALL_STATIONS, ADD_STATION, UPDATE_STATION, REMOVE_STATION,
    GET_ALL_TRAINS, ADD_TRAIN, UPDATE_TRAIN, REMOVE_TRAIN,
    GET_ALL_SCHEDULES, ADD_SCHEDULE, UPDATE_SCHEDULE, REMOVE_SCHEDULE,
    SEARCH_AVAILABLE, SEARCH_JOURNEYS, BOOK_SEATS, GET_ALL_BOOKINGS, GET_MY_BOOKINGS
}
