package networking;

public enum ResponseType {
    OK, ERROR,
    UPDATED, ADDED, REMOVED,
    STATION_ADDED, STATION_UPDATED, STATION_REMOVED,
    TRAIN_ADDED, TRAIN_UPDATED, TRAIN_REMOVED,
    SCHEDULE_ADDED, SCHEDULE_UPDATED, SCHEDULE_REMOVED,
    BOOKING_ADDED
}
